# Generated by Django 5.2.7 on 2025-11-26 04:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('USER_LOGIN', 'User Login'), ('USER_LOGOUT', 'User Logout'), ('LOGIN_FAILED', 'Login Failed'), ('AUTH_REQUEST', 'Authentication Request'), ('AUTH_COMPLETED', 'Authentication Completed'), ('AUTH_FAILED', 'Authentication Failed'), ('AUTH_EXPIRED', 'Authentication Expired'), ('AUTH_STATUS_CHANGE', 'Authentication Status Change'), ('USER_INFO_UPDATE', 'User Information Update'), ('CI_DI_ACCESS', 'CI/DI Data Access'), ('ADMIN_ACTION', 'Administrator Action'), ('SERVICE_PROVIDER_CREATE', 'Service Provider Created'), ('SERVICE_PROVIDER_UPDATE', 'Service Provider Updated'), ('ROLE_ASSIGNMENT', 'Role Assignment')], db_index=True, help_text='Type of action performed', max_length=50)),
                ('details', models.TextField(help_text='Detailed description of the action')),
                ('ip_address', models.GenericIPAddressField(help_text='IP address of the client')),
                ('user_agent', models.CharField(blank=True, help_text='User agent string of the client', max_length=255)),
                ('request_path', models.CharField(blank=True, help_text='API endpoint or page accessed', max_length=500)),
                ('request_method', models.CharField(blank=True, help_text='HTTP method (GET, POST, etc.)', max_length=10)),
                ('status_code', models.IntegerField(blank=True, help_text='HTTP status code of the response', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the action occurred')),
                ('user', models.ForeignKey(blank=True, help_text='User who performed the action (null for system actions)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'db_table': 'audit_logs_auditlog',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='idx_audit_user_time'), models.Index(fields=['action', '-timestamp'], name='idx_audit_action_time'), models.Index(fields=['-timestamp'], name='idx_audit_timestamp'), models.Index(fields=['ip_address', '-timestamp'], name='idx_audit_ip')],
            },
        ),
    ]
