# Generated by Django 5.2.7 on 2025-11-26 04:15

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.CharField(help_text="Name of the service (e.g., 'A Shopping Mall')", max_length=200)),
                ('client_id', models.CharField(db_index=True, help_text='Public identifier for the service', max_length=64, unique=True)),
                ('client_secret', models.CharField(help_text='Hashed secret key for authentication', max_length=255)),
                ('callback_url', models.URLField(help_text='URL to receive authentication results', max_length=500, validators=[django.core.validators.URLValidator()])),
                ('encryption_algorithm', models.CharField(default='AES-256-GCM', help_text='Encryption algorithm for data transmission', max_length=50)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether this service provider is currently active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Provider',
                'verbose_name_plural': 'Service Providers',
                'db_table': 'services_serviceprovider',
                'indexes': [models.Index(fields=['client_id'], name='idx_sp_client_id'), models.Index(fields=['is_active', '-created_at'], name='idx_sp_active')],
                'constraints': [models.CheckConstraint(condition=models.Q(('is_active__in', [True, False])), name='chk_sp_active')],
            },
        ),
        migrations.CreateModel(
            name='EncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_name', models.CharField(help_text='Identifier for this key', max_length=100)),
                ('key_value', models.TextField(help_text='Encrypted key value')),
                ('algorithm', models.CharField(default='AES-256-GCM', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Key expiration date (optional)', null=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encryption_keys', to='services.serviceprovider')),
            ],
            options={
                'verbose_name': 'Encryption Key',
                'verbose_name_plural': 'Encryption Keys',
                'db_table': 'services_encryptionkey',
                'indexes': [models.Index(fields=['service_provider', 'is_active'], name='idx_key_sp_active')],
                'unique_together': {('service_provider', 'key_name')},
            },
        ),
        migrations.CreateModel(
            name='ServiceProviderStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('total_requests', models.IntegerField(default=0)),
                ('completed_requests', models.IntegerField(default=0)),
                ('failed_requests', models.IntegerField(default=0)),
                ('expired_requests', models.IntegerField(default=0)),
                ('success_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Success rate in percentage', max_digits=5)),
                ('avg_processing_time', models.DecimalField(decimal_places=2, default=0.0, help_text='Average processing time in seconds', max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='services.serviceprovider')),
            ],
            options={
                'verbose_name': 'Service Provider Statistics',
                'verbose_name_plural': 'Service Provider Statistics',
                'db_table': 'services_serviceproviderstatistics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['service_provider', '-date'], name='idx_stats_sp_date')],
                'unique_together': {('service_provider', 'date')},
            },
        ),
    ]
