# Generated by Django 5.2.7 on 2025-11-26 04:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthTransaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier for this authentication transaction', primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='When the authentication request was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last update time')),
                ('expires_at', models.DateTimeField(db_index=True, help_text='When this transaction expires (typically 3 minutes)')),
                ('auth_code', models.CharField(blank=True, help_text='One-time authorization code generated upon successful authentication', max_length=64, null=True, unique=True)),
                ('failure_reason', models.TextField(blank=True, help_text='Reason for failure (if status is FAILED)')),
                ('service_provider', models.ForeignKey(help_text='Service requesting authentication', on_delete=django.db.models.deletion.RESTRICT, related_name='auth_transactions', to='services.serviceprovider')),
                ('user', models.ForeignKey(help_text='User being authenticated', on_delete=django.db.models.deletion.RESTRICT, related_name='auth_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Authentication Transaction',
                'verbose_name_plural': 'Authentication Transactions',
                'db_table': 'auth_transactions_authtransaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('AUTH_REQUEST', 'Authentication Request'), ('AUTH_SUCCESS', 'Authentication Success'), ('AUTH_FAILED', 'Authentication Failed'), ('AUTH_EXPIRED', 'Authentication Expired')], db_index=True, max_length=20)),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('FAILED', 'Failed')], default='PENDING', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='auth_transactions.authtransaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'auth_transactions_notificationlog',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='authtransaction',
            index=models.Index(fields=['status', 'expires_at'], name='idx_tx_status_expires'),
        ),
        migrations.AddIndex(
            model_name='authtransaction',
            index=models.Index(fields=['user', '-created_at'], name='idx_tx_user_created'),
        ),
        migrations.AddIndex(
            model_name='authtransaction',
            index=models.Index(fields=['service_provider', '-created_at'], name='idx_tx_sp_created'),
        ),
        migrations.AddIndex(
            model_name='authtransaction',
            index=models.Index(fields=['created_at'], name='idx_tx_created_at'),
        ),
        migrations.AddConstraint(
            model_name='authtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['PENDING', 'COMPLETED', 'FAILED', 'EXPIRED'])), name='chk_status_values'),
        ),
        migrations.AddConstraint(
            model_name='authtransaction',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='chk_expires_after_created'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['user', '-created_at'], name='idx_notif_user'),
        ),
        migrations.AddIndex(
            model_name='notificationlog',
            index=models.Index(fields=['transaction', '-created_at'], name='idx_notif_tx'),
        ),
    ]
