# Generated by Django 5.2.7 on 2025-11-26 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authtransaction',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, help_text='When the user confirmed/rejected this transaction', null=True),
        ),
    ]
